feature ERP-774: add policy stage

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -1,17 +1,57 @@
-image: docker:20.10.7  # Imagen base estándar de Docker
+image: maven:3.8.4  # Usa Maven como imagen base para las etapas que lo requieran
 
 clone:
   depth: full
 
 definitions:
   steps:
+    # Paso para la validación de ramas con Git Police
+    - step: &git-police
+        name: Git Police Step
+        script:
+          - printenv
+          - echo "-------------------------------------------------------------------------"
+          - echo "${DOCKERHUB_PASSWORD}" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+          - docker run -d -p 5000:5000 -e REPO_TOKEN="${ETENDOBOT_TOKEN}" -e PR_ID="$BITBUCKET_PR_ID" -e REPO_NAME="$BITBUCKET_REPO_SLUG" etendo/gitpolice:"${GITPOLICE_VERSION}"
+          - echo "-------------------------------------------------------------------------"
+          - sleep 10s
+          - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/api/bitbucket)
+          - |
+            if [ "$response" -ne 200 ]; then
+              echo "API call failed with status code $response"
+              cat response.txt
+              exit 1
+            fi
+          - |
+            if ! grep -q "Valid branch name and correct destination" response.txt; then
+              echo "Git Police check failed: response does not contain 'Valid branch name and correct destination'"
+              echo "Full response:"
+              cat response.txt
+              exit 1
+            fi
+          - echo "API call successful with status code $response"
+          - cat response.txt
+        services:
+          - docker
+
+    # Análisis de SonarQube
+    - step: &build-step
+        name: SonarQube analysis
+        script:
+          - pipe: sonarsource/sonarqube-scan:1.0.0
+            variables:
+              SONAR_HOST_URL: ${SONAR_HOST_URL}
+              SONAR_TOKEN: ${SONAR_TOKEN}
+              SONAR_EXCLUDE: node_modules, android, ios
+
+    # Revisión de código automatizada
     - step: &make-review
         name: Make Review Step
         script:
           - printenv
           - echo "-------------------------------------------------------------------------"
-          - echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
-          - docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST="${BITBUCKET_PR_ID}" -e PROJECT="${BITBUCKET_REPO_OWNER}" -e REPO_SLUG="${BITBUCKET_REPO_SLUG}" -e OPENAI_API_KEY="${OPENAI_API_KEY}" etendo/code-reviewer:"${REVIEWER_VERSION}"
+          - echo "${DOCKERHUB_PASSWORD}" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+          - docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST=$BITBUCKET_PR_ID -e PROJECT=$BITBUCKET_REPO_OWNER -e REPO_SLUG=$BITBUCKET_REPO_SLUG -e OPENAI_API_KEY=$OPENAI_API_KEY etendo/code-reviewer:${REVIEWER_VERSION}
           - echo "-------------------------------------------------------------------------"
           - sleep 10s
           - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/review/bitbucket)
@@ -26,61 +66,78 @@ definitions:
         services:
           - docker
 
-    - step: &build-step
-        name: SonarQube analysis
-        script:
-          - pipe: sonarsource/sonarqube-scan:1.0.0
-            variables:
-              SONAR_HOST_URL: ${SONAR_HOST_URL}
-              SONAR_TOKEN: ${SONAR_TOKEN}
-              SONAR_EXCLUDE: node_modules, android, ios
+    # Construcción y despliegue para amd64
+    - step: &build-push-amd64
+      name: Build and Push for amd64
+      script:
+        - |
+          if [[ "${BITBUCKET_BRANCH}" == "develop" || "${BITBUCKET_BRANCH}" == "master" || "${BITBUCKET_BRANCH}" == "experimental" ]]; then
+            BRANCH_NAME=${BITBUCKET_BRANCH}
+          else
+            BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')
+          fi
+        - echo "${DOCKERHUB_PASSWORD}" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+        - IMAGE=test-lucas/dynamic-gradle:${BRANCH_NAME}-amd64
+        - docker build --platform linux/amd64 -t ${IMAGE} .
+        - docker push ${IMAGE}
+      services:
+        - docker
 
-    - step: &build-push-images
-        name: Build and Push Docker Images (amd64 and arm64)
-        caches:
-          - docker
-        services:
-          - docker
-        script:
-          # Crea un builder con soporte para multi-arquitectura
-          - docker buildx create --use  
-          - docker buildx inspect --bootstrap  # Verifica que el builder esté listo
-          - docker run --rm --privileged aptman/qus -s -- -p  # Instala QEMU static (multi-arquitectura)
-          - export VERSION=$(cat VERSION)  
-         
-          # Build and push for dynamic-gradle with a custom name for testing
-          - echo "Building amd64 and arm64 images for dynamic-gradle"
-          - docker buildx build --platform linux/amd64,linux/arm64 -t test-lucas/dynamic-gradle:${VERSION} --push .
-          
-          # Build and push for dynamic-das with a custom name for testing
-          - echo "Building amd64 and arm64 images for dynamic-das"
-          - docker buildx build --platform linux/amd64,linux/arm64 -t test-lucas/dynamic-das:${VERSION} --push .
+    # Construcción y despliegue para arm64
+    - step: &build-push-arm64
+      name: Build and Push for arm64
+      runs-on:
+        - self.hosted
+        - linux.arm64
+      script:
+        - |
+          if [[ "${BITBUCKET_BRANCH}" == "develop" || "${BITBUCKET_BRANCH}" == "master" || "${BITBUCKET_BRANCH}" == "experimental" ]]; then
+            BRANCH_NAME=${BITBUCKET_BRANCH}
+          else
+            BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')
+          fi
+        - echo "${DOCKERHUB_PASSWORD}" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+        - IMAGE=test-lucas/dynamic-das:${BRANCH_NAME}-arm64
+        - docker build --platform linux/arm64/v8 -t ${IMAGE} .
+        - docker push ${IMAGE}
+      services:
+        - docker
 
-          # Create and push Docker manifest for dynamic-gradle
-          - echo "Creating and pushing manifest for multi-arch support for dynamic-gradle"
-          - docker manifest create test-lucas/dynamic-gradle:${VERSION} test-lucas/dynamic-gradle:${VERSION}-amd64 test-lucas/dynamic-gradle:${VERSION}-arm64
-          - docker manifest push test-lucas/dynamic-gradle:${VERSION}
-
-          # Create and push Docker manifest for dynamic-das
-          - echo "Creating and pushing manifest for multi-arch support for dynamic-das"
-          - docker manifest create test-lucas/dynamic-das:${VERSION} test-lucas/dynamic-das:${VERSION}-amd64 test-lucas/dynamic-das:${VERSION}-arm64
-          - docker manifest push test-lucas/dynamic-das:${VERSION}
+    # Crear y subir manifiesto multi-arquitectura
+    - step: &create-push-manifest
+      name: Create and Push Manifest
+      script:
+        - |
+          if [[ "${BITBUCKET_BRANCH}" == "develop" || "${BITBUCKET_BRANCH}" == "master" || "${BITBUCKET_BRANCH}" == "experimental" ]]; then
+            BRANCH_NAME=${BITBUCKET_BRANCH}
+          else
+            BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')
+          fi
+        - echo "${DOCKERHUB_PASSWORD}" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+        - docker pull test-lucas/dynamic-gradle:${BRANCH_NAME}-amd64
+        - docker pull test-lucas/dynamic-das:${BRANCH_NAME}-arm64
+        - docker manifest create test-lucas/dynamic:${BRANCH_NAME} test-lucas/dynamic-gradle:${BRANCH_NAME}-amd64 test-lucas/dynamic-das:${BRANCH_NAME}-arm64
+        - docker manifest annotate test-lucas/dynamic:${BRANCH_NAME} test-lucas/dynamic-gradle:${BRANCH_NAME}-amd64 --os linux --arch amd64
+        - docker manifest annotate test-lucas/dynamic:${BRANCH_NAME} test-lucas/dynamic-das:${BRANCH_NAME}-arm64 --os linux --arch arm64
+        - docker manifest push test-lucas/dynamic:${BRANCH_NAME}
+      services:
+        - docker
 
   caches:
     sonar: ~/.sonar
 
 pipelines:
   branches:
-    'feature/ERP-774':  
+    feature/ERP-774:  # Cambié la rama de trigger para pruebas
       - step: *build-step
-      - step: *build-push-images  
+      - parallel:
+          - step: *build-push-amd64
+          - step: *build-push-arm64
+      - step: *create-push-manifest
+
   pull-requests:
-    'develop':
-      - step:
-          script:
-            - echo "Skip for develop branch"
-            - exit 0
-    '**':
+    "**":
+      - step: *git-police
       - parallel:
           - step: *make-review
           - step: *build-step
