Update Jenkins pod name and improve installation commands JIRA-CODE
- Changed pod name to 'jenkins-node-0' for clarity.
- Enhanced installation commands to ensure docker and curl/openssl are installed correctly.

diff --git a/pipelines/Jenkinsfile b/pipelines/Jenkinsfile
--- a/pipelines/Jenkinsfile
+++ b/pipelines/Jenkinsfile
@@ -66,7 +66,7 @@ pipeline {
 apiVersion: v1
 kind: Pod
 metadata:
-  name: jenkins-node
+  name: jenkins-node-0
   namespace: jenkins2025
   labels:
     app.kubernetes.io/name: jenkins-node
@@ -98,11 +98,14 @@ spec:
           exec:
             command:
               - bash
-              - '-c'
-              - >-
-                chmod a+x /var/run/docker.sock && rm
-                /etc/apt/sources.list.d/pgdg.list || echo 0 && apt update && apt
-                install -y curl
+              - '-lc'
+              - |
+                set -e
+                  (apt-get update -y || true)
+                  if ! command -v docker >/dev/null 2>&1; then
+                    (apt-get install -y docker.io || echo "⚠️ Couldn't install docker")
+                  fi
+                  (apt-get install -y curl openssl || echo "⚠️ Couldn't install curl/openssl")
       terminationMessagePath: /dev/termination-log
       terminationMessagePolicy: File
       imagePullPolicy: IfNotPresent
